### ISSUE TITLE
RuntimeError in python 3.9 with multiple processes

### ISSUE THREAD

**Issue by kfuku52** [kfuku52/csubst#19]
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/kef74yk/opt/miniconda3/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/kef74yk/opt/miniconda3/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Users/kef74yk/opt/miniconda3/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Users/kef74yk/opt/miniconda3/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/Users/kef74yk/opt/miniconda3/lib/python3.9/runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Users/kef74yk/opt/miniconda3/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Users/kef74yk/opt/miniconda3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/kef74yk/Dropbox_p/repos/csubst/csubst/csubst", line 283, in <module>
    args.handler(args)
  File "/Users/kef74yk/Dropbox_p/repos/csubst/csubst/csubst", line 47, in command_analyze
    main_analyze(g)
  File "/Users/kef74yk/Dropbox (Personal)/repos/csubst/csubst/main_analyze.py", line 273, in main_analyze
    g = cb_search(g, b, S_tensor, N_tensor, id_combinations, mode='foreground', write_cb=True)
  File "/Users/kef74yk/Dropbox (Personal)/repos/csubst/csubst/main_analyze.py", line 99, in cb_search
    cbS = substitution.get_cb(id_combinations, S_tensor, g, 'S')
  File "/Users/kef74yk/Dropbox (Personal)/repos/csubst/csubst/substitution.py", line 174, in get_cb
    joblib.Parallel(n_jobs=g['threads'], max_nbytes=None, backend='multiprocessing')(
  File "/Users/kef74yk/opt/miniconda3/lib/python3.9/site-packages/joblib/parallel.py", line 966, in __call__
    n_jobs = self._initialize_backend()
  File "/Users/kef74yk/opt/miniconda3/lib/python3.9/site-packages/joblib/parallel.py", line 733, in _initialize_backend
    n_jobs = self._backend.configure(n_jobs=self.n_jobs, parallel=self,
  File "/Users/kef74yk/opt/miniconda3/lib/python3.9/site-packages/joblib/_parallel_backends.py", line 470, in configure
    self._pool = MemmappingPool(n_jobs, **memmappingpool_args)
  File "/Users/kef74yk/opt/miniconda3/lib/python3.9/site-packages/joblib/pool.py", line 323, in __init__
    super(MemmappingPool, self).__init__(**poolargs)
  File "/Users/kef74yk/opt/miniconda3/lib/python3.9/site-packages/joblib/pool.py", line 205, in __init__
    super(PicklingPool, self).__init__(**poolargs)
  File "/Users/kef74yk/opt/miniconda3/lib/python3.9/multiprocessing/pool.py", line 212, in __init__
    self._repopulate_pool()
  File "/Users/kef74yk/opt/miniconda3/lib/python3.9/multiprocessing/pool.py", line 303, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "/Users/kef74yk/opt/miniconda3/lib/python3.9/multiprocessing/pool.py", line 326, in _repopulate_pool_static
    w.start()
  File "/Users/kef74yk/opt/miniconda3/lib/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/kef74yk/opt/miniconda3/lib/python3.9/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Users/kef74yk/opt/miniconda3/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/kef74yk/opt/miniconda3/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/kef74yk/opt/miniconda3/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/Users/kef74yk/opt/miniconda3/lib/python3.9/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/Users/kef74yk/opt/miniconda3/lib/python3.9/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

```

**Comment by kfuku52** [comment]
https://stackoverflow.com/questions/55057957/an-attempt-has-been-made-to-start-a-new-process-before-the-current-process-has-f
