### ISSUE TITLE
AttributeError: 'bool' object has no attribute 'sum'

### ISSUE THREAD

**Issue by kfuku52** [kfuku52/csubst#25]
With pandas 1.5.0:
```
--cutoff_stat specification "{}" is omitted. Check the format carefully.
--cutoff_stat specification "{}" is omitted. Check the format carefully.
Traceback (most recent call last):
  File "/opt/conda/envs/biotools/bin/csubst", line 316, in <module>
    args.handler(args)
  File "/opt/conda/envs/biotools/bin/csubst", line 43, in command_analyze
    main_analyze(g)
  File "/opt/conda/envs/biotools/lib/python3.9/site-packages/csubst/main_analyze.py", line 263, in main_analyze
    g,cb = cb_search(g, b, S_tensor, N_tensor, id_combinations, mode='foreground', write_cb=True)
  File "/opt/conda/envs/biotools/lib/python3.9/site-packages/csubst/main_analyze.py", line 98, in cb_search
    cb, g = foreground.get_foreground_branch_num(cb, g)
  File "/opt/conda/envs/biotools/lib/python3.9/site-packages/csubst/foreground.py", line 317, in get_foreground_branch_num
    num_enough = is_enough_stat.sum()
AttributeError: 'bool' object has no attribute 'sum'
```

**Comment by kfuku52** [comment]
The version of pandas was not relevant. This error likely happens when --cutoff_stat is mis-specified.
