### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get_leaf_names'

### ISSUE THREAD

**Issue by kfuku52** [kfuku52/csubst#32]
```
Traceback (most recent call last):
  File "/opt/conda/envs/biotools/bin/csubst", line 324, in <module>
    args.handler(args)
  File "/opt/conda/envs/biotools/bin/csubst", line 43, in command_analyze
    main_analyze(g)
  File "/opt/conda/envs/biotools/lib/python3.9/site-packages/csubst/main_analyze.py", line 134, in main_analyze
    g = combination.get_dep_ids(g)
  File "/opt/conda/envs/biotools/lib/python3.9/site-packages/csubst/combination.py", line 234, in get_dep_ids
    is_up_all_leaf_lineage_fg = all([ ln in g['fg_leaf_name'][i] for ln in node.up.get_leaf_names() ])
AttributeError: 'NoneType' object has no attribute 'get_leaf_names'
```

**Comment by kfuku52** [comment]
```
CSUBST start: 2023-03-07 21:35:29.563298+00:00
csubst analyze start: 2023-03-07 21:35:29.567451+00:00
OS: Linux-3.10.0-1160.el7.x86_64-x86_64-with-glibc2.24
Python version: 3.9.15 | packaged by conda-forge | (main, Nov 22 2022, 08:45:29)  [GCC 10.4.0]
CSUBST version: 1.3.4
CSUBST command: /opt/conda/envs/biotools/bin/csubst analyze --genetic_code 1 --infile_type iqtree --alignment_file ./OG0000356.iqtree.anc/csubst.fasta --rooted_tree_file ./OG0000356.iqtree.anc/csubst.nwk --iqtree_treefile ./OG0000356.iqtree.anc/csubst.treefile --iqtree_state ./OG0000356.iqtree.anc/csubst.state --iqtree_rate ./OG0000356.iqtree.anc/csubst.rate --iqtree_iqtree ./OG0000356.iqtree.anc/csubst.iqtree --iqtree_log ./OG0000356.iqtree.anc/csubst.log --iqtree_model ECMK07+F+R4 --iqtree_redo no --max_arity 10 --exhaustive_until 1 --cutoff_stat OCNany2spe,2.0|omegaCany2spe,5.0 --max_combination 10000 --fg_exclude_wg yes --fg_stem_only no --mg_sister no --exclude_sister_pair yes --ml_anc no --b yes --s no --cs no --cb yes --bs no --cbs no --calc_quantile no --omegaC_method submodel --asrv each --threads 2 --calibrate_longtail yes --float_type 32 --foreground foreground.txt
CSUBST working directory: /gfe_data/orthogroup/tmp/112_OG0000356
CSUBST bug report: https://github.com/kfuku52/csubst/issues
Reading and parsing input files.
Using internal node names and branch lengths in --iqtree_treefile and the root position in --rooted_tree_file.
IQ-TREE's intermediate files exist.
The model in the IQ-TREE's output (ECMK07+F+R4) matched --iqtree_model (ECMK07+F+R4). Skipping IQ-TREE.
Total branch length of --rooted_tree_file: 0.1447
Total branch length of --iqtree_treefile: 0.1877

Reading the state file: ./OG0000356.iqtree.anc/csubst.state

Instantaneous substitution rate matrix will be generated using the base model: ECMK07+F
Transition matrix will be generated using the model in the ancestral state reconstruction: ECMK07+F+R4
Applying estimated codon frequencies to obtain the instantaneous rate matrix.
Writing sequence alignment: csubst_alignment_codon.fa
Writing sequence alignment: csubst_alignment_aa.fa
Ancestral states were not estimated on the root node. Excluding sub-root nodes from the analysis.
```
