### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by kfuku52** [kfuku52/csubst#57]
```
Traceback (most recent call last):
  File "/home/kfuku/mambaforge/bin/csubst", line 329, in <module>
    args.handler(args)
  File "/home/kfuku/mambaforge/bin/csubst", line 34, in command_site
    main_site(g)
  File "/lustre7/home/lustre4/kfuku/mambaforge/lib/python3.10/site-packages/csubst/main_site.py", line 696, in main_site
    parser_pymol.write_pymol_session(df=df, g=g)
  File "/lustre7/home/lustre4/kfuku/mambaforge/lib/python3.10/site-packages/csubst/parser_pymol.py", line 311, in write_pymol_session
    mask_subunit(g)
  File "/lustre7/home/lustre4/kfuku/mambaforge/lib/python3.10/site-packages/csubst/parser_pymol.py", line 218, in mask_subunit
    pymol.cmd.do('color {}, chain {} and polymer.protein'.format(colors[i], chain))
IndexError: list index out of range
```

**Comment by kfuku52** [comment]
```
OS: Linux-3.10.0-1160.el7.x86_64-x86_64-with-glibc2.17
Python version: 3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:40:32) [GCC 12.3.0]
CSUBST version: 1.4.4
CSUBST command: /home/kfuku/mambaforge/bin/csubst site --alignment_file HOG0002315.iqtree.anc/csubst.fasta --rooted_tree_file HOG0002315.iqtree.anc/csubst.nwk --branch_id 130,362,364 --ml_anc no --threads 2 --iqtree_treefile /lustre7/home/lustre4/kfuku/my_project/Shigehiro_Kuraku/20231006_shark_convergence/gfe_pipeline/csubst_site_Oviparous-chondrichthyan_K3_minOCN1.8_minomegaC3.0_minOCNCoD0.0/HOG0002315_130_362_364/HOG0002315.iqtree.anc/csubst.treefile --iqtree_state /lustre7/home/lustre4/kfuku/my_project/Shigehiro_Kuraku/20231006_shark_convergence/gfe_pipeline/csubst_site_Oviparous-chondrichthyan_K3_minOCN1.8_minomegaC3.0_minOCNCoD0.0/HOG0002315_130_362_364/HOG0002315.iqtree.anc/csubst.state --iqtree_rate /lustre7/home/lustre4/kfuku/my_project/Shigehiro_Kuraku/20231006_shark_convergence/gfe_pipeline/csubst_site_Oviparous-chondrichthyan_K3_minOCN1.8_minomegaC3.0_minOCNCoD0.0/HOG0002315_130_362_364/HOG0002315.iqtree.anc/csubst.rate --iqtree_iqtree /lustre7/home/lustre4/kfuku/my_project/Shigehiro_Kuraku/20231006_shark_convergence/gfe_pipeline/csubst_site_Oviparous-chondrichthyan_K3_minOCN1.8_minomegaC3.0_minOCNCoD0.0/HOG0002315_130_362_364/HOG0002315.iqtree.anc/csubst.iqtree --iqtree_log /lustre7/home/lustre4/kfuku/my_project/Shigehiro_Kuraku/20231006_shark_convergence/gfe_pipeline/csubst_site_Oviparous-chondrichthyan_K3_minOCN1.8_minomegaC3.0_minOCNCoD0.0/HOG0002315_130_362_364/HOG0002315.iqtree.anc/csubst.log --mafft_exe mafft --pdb besthit
CSUBST working directory: /lustre7/home/lustre4/kfuku/my_project/Shigehiro_Kuraku/20231006_shark_convergence/gfe_pipeline/csubst_site_Oviparous-chondrichthyan_K3_minOCN1.8_minomegaC3.0_minOCNCoD0.0/HOG0002315_130_362_364
```
